keystore: export the generated "*.h" file path of keystore aidl interface
for project that using keystore's client interface, also need the the
generated header file of keystore's AIDL interface, so we need to export
the AIDL interface to fix the following build error:
In file included from /home/vela/work_profile/vela_os/vela_qemu_miwear/apps/frameworks/runtimes/feature/modules/assetstore_impl.cpp:32:
/home/vela/work_profile/vela_os/vela_qemu_miwear/apps/external/android/system/security/keystore/include/keystore/keystore_client_impl.h:26:10: fatal error: android/security/keystore/IKeystoreService.h: No such file or directory
   26 | #include <android/security/keystore/IKeystoreService.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: guoshichao <guoshichao@xiaomi.com>